name: Feature Request
description: Suggest a feature or improvement idea for the app
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Suggest a feature or improvement idea for the app
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: App version
      description: What version of the app this request is for?
      options:
        - v1
        - v2
      default: 1
    validations:
      required: true
